<!--Section-->
<section id="home">
      <div class="container">
        <div class="row">
          <!--Textos da section-->
          <div class="col-md-6 d-flex">
            <div class="align-self-center">
              <h1 class="display-4">Suas contas, descomplicadas</h1>
              <p>Usado por mais de 1 milhão de pessoas, o Finans é uma ferramenta online que vai facilitar sua vida financeira</p>
                <div class="d-grid gap-2 d-md-block">
                    <a href="/inscreverse"><buton class="btn btn-success btn-lg w-50 m-4" type="button">Cadastre-se</buton></a>
                </div>
             
              <p>Disponível para
                <a class="btn btn-outline-success"href="#">
                  <i class="fab fa-android fa-lg"></i>
                </a>
                <a class="btn btn-outline-success"href="#">
                  <i class="fab fa-apple fa-lg"></i>
                </a>
              </p>
            </div>
          </div>
          <div class="mt-5 col-md-6 p-5 d-none d-md-block">
            <img  class=" img-fluid rounded" src="/img/natureIMGR.jpg" alt="">
          </div>
        </div>
      <!--Fim Section-->
    </section>
    <hr>
     <!--Início  Seção Saiba-->
     <section class="caixa">
      <div class="container">
        <div class="row" style="height:400px;">
          <div class="col-md-6 d-flex">
            <div class="align-self-center animeRight">
              <h2>Saiba para onde vai o seu dinheiro</h2>
              <p>Com o Finans, você categoriza todos os seus lançamentos. Com gráficos simples, você sabe de onde vem e para onde vai o seu dinheiro.</p>
              <div class="d-flex justify-content-center">
                <a class=" btn btn-outline-success btn-lg "href="">Veja mais</a>
              </div>
            </div>
          </div>
          <div class="col-md-6 d-none d-md-block">
          <img  class="animeLeft img-fluid rounded" src="/img/naturezaLataR.jpg" alt="">
          </div>
        </div>
      </div>
    </section>
    <!--Fim section saiba-->
  <!--Início  Seção juros-->
  <section class="caixa">
   <div class="container">
     <div class="row" style="height:400px;">
       <div class="col-md-6  d-none d-md-block">
       <img  class="animeRight img-fluid rounded" src="/img/naturezaLixoR.jpg" alt="">
       </div>
       <div class="col-md-6 d-flex">
        <div class="align-self-center animeLeft">
          <h2>Pare de pagar juros e economize</h2>
          <p>Manter as contas em dia é sempre um problema? O Finans avisa você: Recebe alertas de contas a pagar e a receber!</p>
          <div class="d-flex justify-content-center">
            <a class="btn btn-outline-success btn-lg"href="">Veja mais</a>
          </div>
        </div>
       </div>
     </div>
   </div>
   <!--Fim Seção juros-->
  <section class="caixa box">
    <div class="container">
      <div class="row">
        <div class="col-md-4 animeTop">
          <h4>Fácil de usar</h4>
          <p>O Finans vai lém do báisoc e permite que você faça controles incríveis, essenciais para suas finanças. Simples como tem que ser!</p>
        </div>
        <div class="col-md-4 animeTop">
          <img class="img-fluid"src="" alt="">
          <h4>Economize seu tempo</h4>
          <p>Tempo é dinheiro! EM segundos, você tem tudo sob controle e aproveite seu tempo com o que realmente import apara você!</p>
        </div>
        <div class="col-md-4 animeTop">
          <img class="img-fluid"src="" alt="">
          <h4>Suporte amigo</h4>
          <p>Dúvidas? Perguntas? Nosso suporte super legal ajuda você! A gente tá aqui pra resolver seus problemas e deixar sua vida bem mais fácil!</p>
        </div>
      </div>
    </div>
  </section>
  <!--Fim Section juros-->