
            
            <div class="row justify-content-center align-items-center formulario">
    
                <div class="col-md-5">
                    <fieldset>
                        <legend class="h1 titulo-ins">Cadastro de Usuário</legend>
                        <form class="row g-3 form" action="/registrar" method="post">
                            <div class="col-md-12">
                            <?php if($this->view->CadastroErro['erronome'] == false){ ?> 
                                    <span class="text text-danger">* Nome de usuário errado</span>
                            <?php } ?>
                                <input style="width:300px;" type="text" value="<?php echo $this->view->usuario['nome']?>" name="nome" placeholder="Nome Completo" class="form-control" id="inputEmail4">
                            </div>
                            
                            <div class="col-md-12">
                                <input style="width:300px;" type="password" name="senha" placeholder="Senha" class="form-control" id="inputPassword4">
                            </div>
                            <div class="col-md-12">
                                <input style="width:300px;" type="password" name="csenha" placeholder="Confirmar Senha" class="form-control" id="inputPassword4">
                            </div>
                            <div class="col-md-12">
                                <?php if($this->view->CadastroErro['errocep'] == false){ ?>
                                    <span class="text text-danger">*Erro cep: formato (9999999)</span>
                                <?php } ?>
                                <input type="text" style="width:200px; value="<?php echo $this->view->usuario['cep']?>"name="cep" class="form-control" id="inputCity" placeholder="CEP">
                               
                            </div>
                            <div class="col-md-12">
                                <input style="width:200px;"type="text" value="<?php echo $this->view->usuario['numero']?>"name="numero" class="form-control" id="inputCity" placeholder="Número">
                            </div>
    
                            <div class="col-md-12">
                                <input style="width:200px; type="text" name="cidade" class="form-control" id="inputCity" placeholder="Cidade">
                            </div>
                            <div class="col-12">
                               
                                <input style="width:400px;" type="text"value="<?php echo $this->view->usuario['endereco']?>" name="endereco" class="form-control" id="inputAddress" placeholder="Endereço">
                            </div>
                            <div class="col-12">
                         
                                <input style="width:300px;" type="text" value="<?php echo $this->view->usuario['complemento']?>"name="complemento" class="form-control" id="inputAddress2" placeholder="Complemento">
                            </div>
                            
                            
                            <div class="col-12">
                                <button type="submit" class="btn btn-success w-100">Cadastrar</button>
                            </div>
                        </form>
                    </fieldset>
                </div>
        </div>