  
<section>
    <div class="container">
        <div class="col"><h2></h2>
    <figure class="figure">
    <img src=".../400x300" class="figure-img img-fluid rounded" alt="Imagem de um quadrado genérico com bordas arredondadas, em uma figure.">
  <figcaption class="figure-caption text-right">Uma legenda para a imagem acima.</figcaption>
 </figure> >


  <h4>Nossa Missão</h4>

  <p>A mutiraê é um plataforma que mobiliza pessoas através de mutirões para ajudar
    aqueles que precisam de ajuda próximos a sua localidade. Iniciado na região de Ramos,
    no Rio de Janeiro. Nossa ideia, surgiu pois em algumas áreas da região, sofrem com a
    falta de coleta de lixo, por parte da Comlub.</p><br>

   <h4>Visão</h4>

   <p>Perceber impactos positivos de inclusão e transformação ambiental na vida dos
   moradores e adjacências onde os mutirões forem realizados.<p></p><br>

   <h4>Valores</h4>

   <p>Ajudar a comunidade na coleta e descarte de lixo de forma correta, ajudando o meio ambiente 
   e reciclagem dos matérias recolhidos. Para os voluntários</p><br>

   <h4>Equipe</h4>

   <p><b>Líder</b> - Jasmine Guimarães</p>
   <p><b>Líder</b> – Pablo Mesquita</p>
   <p><b>Allan Jales, Aline Ribeiro e Mayara Braga</b></p></div></div>

   <br><br><br>

    </section>
   </html>

